version: '3.5'

services:
  apis:
    container_name: company.dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
      args:
        PORT: ${PORT}
        DEBUGGER_PORT: ${DEBUGGER_PORT}
    volumes:
      - .:/usr/src/app/company-app
      - /usr/src/app/company-app/node_modules
    ports:
      - ${PORT}:${PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    links:
      - database:${DATABASE_HOST}
    depends_on:
      - database
    expose:
      - ${PORT}
      - ${DEBUGGER_PORT}
    env_file:
      - .env.docker

  database:
    container_name: ${DATABASE_HOST}
    image: mysql
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - company-data-db:/var/lib/mysql

volumes:
  company-data-db:
